# Site settings
title: Deep Learning
email: mohsen.dehghani@gmail.com
description: >-
  A blog exploring deep learning, AI, and data science topics by Mohsen Dehghani.
github_username: modeha

# Build settings
usemathjax: true
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
highlighter-theme: monokai
date_format: "%Y-%m-%d"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# URL settings (for GitHub Pages)
# Uncomment if hosted on a subpath or different base URL
# baseurl: "/blog"
# url: "https://modeha.github.io"

# SVG optimization
svg:
  optimize: true

# Directory settings for category and tags
category_dir: category/
tag_dir: tag/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/

theme: jekyll-theme-cayman # minima #jekyll-theme-merlot


